# Generated by Django 6.0.4 on 2026-06-03 08:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsommableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(choices=[('Berceau', 'Berceau'), ('CCB', 'CCB')], default='Berceau', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('reference', models.CharField(max_length=80)),
                ('unit_price_eur', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consommable_item',
                'ordering': ['equipe', 'name', 'reference'],
                'constraints': [models.UniqueConstraint(fields=('equipe', 'reference'), name='uniq_consommable_item_equipe_reference')],
            },
        ),
        migrations.CreateModel(
            name='ConsommablePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(choices=[('Berceau', 'Berceau'), ('CCB', 'CCB')], default='Berceau', max_length=20)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price_eur', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price_eur', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consommable_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='consommable.consommableitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consommable_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consommable_purchase',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
    ]
