# Generated by Django 6.0.4 on 2026-06-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consommable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consommableitem',
            name='uniq_consommable_item_equipe_reference',
        ),
        migrations.AddField(
            model_name='consommableitem',
            name='type_materiel',
            field=models.CharField(choices=[('EPIs', 'EPIs'), ('AUTRE', 'AUTRE'), ('FOURNITURE', 'FOURNITURE'), ('PR BERCEAU', 'PR BERCEAU'), ('PR TORCHE MANULLE', 'PR TORCHE MANULLE'), ('PRODUIT CHIMIQUE', 'PRODUIT CHIMIQUE')], default='AUTRE', max_length=40),
        ),
        migrations.AddField(
            model_name='consommablepurchase',
            name='shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('N', 'N')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='consommableitem',
            constraint=models.UniqueConstraint(fields=('equipe', 'reference', 'name'), name='uniq_consommable_item_equipe_reference_name'),
        ),
    ]
