# Generated by Django 6.0.4 on 2026-04-24 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBerceau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('A1', 'A1'), ('A3', 'A3')], max_length=2, verbose_name='Ligne')),
                ('date', models.DateField(verbose_name='Date')),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Equipe')),
                ('objectif', models.PositiveIntegerField(default=337, verbose_name='Objectif')),
                ('volume', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume')),
                ('rebut', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rebut')),
                ('retouche', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retouche')),
                ('temps_arrets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name="Temps d'arrets")),
            ],
            options={
                'verbose_name': 'Production Berceau',
                'verbose_name_plural': 'Production Berceau',
                'ordering': ['-date', 'line', 'shift'],
                'constraints': [models.UniqueConstraint(fields=('line', 'date', 'shift'), name='uniq_production_berceau_line_date_shift')],
            },
        ),
    ]
