# Generated by Django 6.0.4 on 2026-04-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionberceau',
            options={'ordering': ['-date', 'line', 'shift']},
        ),
    ]
