# Generated by Django 6.0.4 on 2026-04-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_productionberceau_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperateurEffectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=120, verbose_name='Nom')),
                ('cin', models.CharField(max_length=32, unique=True, verbose_name='CIN')),
                ('identifiant', models.CharField(max_length=64, unique=True, verbose_name='Identifiant')),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10, verbose_name='Sexe')),
                ('fonction', models.CharField(choices=[('OP', 'OP'), ('PSP', 'PSP')], max_length=10, verbose_name='Fonction')),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('ANAPEC', 'ANAPEC')], max_length=20, verbose_name='Type de contrat')),
                ('niveau_etude', models.CharField(max_length=120, verbose_name="Niveau d'etude")),
                ('numero_casier', models.CharField(max_length=32, verbose_name='Numero de casier')),
                ('parada_transport', models.CharField(max_length=120, verbose_name='Parada de transport')),
                ('pointure_chaussure', models.CharField(max_length=20, verbose_name='Pointure de chaussure')),
                ('specialite', models.CharField(max_length=120, verbose_name='Specialite')),
                ('taille_pantalon', models.CharField(max_length=20, verbose_name='Taille pantalon')),
                ('taille_veste', models.CharField(max_length=20, verbose_name='Taille veste')),
                ('equipe', models.CharField(choices=[('Berceau', 'Berceau'), ('CCB', 'CCB')], max_length=20, verbose_name='Equipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
