# Generated by Django 6.0.4 on 2026-04-27 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_operateureffectif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionberceau',
            name='line',
            field=models.CharField(choices=[('A1', 'A1'), ('A3', 'A3')], max_length=2, verbose_name='Diversité'),
        ),
        migrations.AlterField(
            model_name='productionberceau',
            name='shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Shift'),
        ),
        migrations.CreateModel(
            name='ProductionCCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Shift')),
                ('objectif', models.PositiveIntegerField(default=337, verbose_name='Objectif')),
                ('volume', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Volume')),
                ('rebut', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rebut')),
                ('retouche', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retouche')),
                ('temps_arrets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name="Temps d'arrets")),
            ],
            options={
                'ordering': ['-date', 'shift'],
                'constraints': [models.UniqueConstraint(fields=('date', 'shift'), name='uniq_production_ccb_date_shift')],
            },
        ),
    ]
