# Generated by Django 6.0.4 on 2026-04-27 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_create_productionccb_if_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionberceau',
            name='objectif_h1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Objectif H1'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='objectif_h2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Objectif H2'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='objectif_h3',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Objectif H3'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='objectif_h4',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Objectif H4'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='objectif_h5',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Objectif H5'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='objectif_h6',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Objectif H6'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='objectif_h7',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Objectif H7'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='objectif_h8',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Objectif H8'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='production_h1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Production H1'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='production_h2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Production H2'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='production_h3',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Production H3'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='production_h4',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Production H4'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='production_h5',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Production H5'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='production_h6',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Production H6'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='production_h7',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Production H7'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='production_h8',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Production H8'),
        ),
    ]
