# Generated by Django 6.0.4 on 2026-04-27 09:44

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productionberceau_objectif_h1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operateureffectif',
            options={'ordering': ['nom_complet']},
        ),
        migrations.RemoveField(
            model_name='operateureffectif',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='operateureffectif',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='operateureffectif',
            name='last_name',
        ),
        migrations.AddField(
            model_name='operateureffectif',
            name='date_entree',
            field=models.DateField(default=datetime.date(2010, 1, 1), verbose_name="Date d'entree"),
        ),
        migrations.AddField(
            model_name='operateureffectif',
            name='date_naissance',
            field=models.DateField(default=datetime.date(1990, 1, 1), verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='operateureffectif',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operateureffectif',
            name='nom_complet',
            field=models.CharField(default='N/A', max_length=180, verbose_name='Nom complet'),
        ),
        migrations.AddField(
            model_name='operateureffectif',
            name='num_tel',
            field=models.CharField(default='+212600000000', max_length=24, verbose_name='Numero de telephone'),
        ),
        migrations.AddField(
            model_name='operateureffectif',
            name='shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, verbose_name='Shift'),
        ),
        migrations.AddField(
            model_name='operateureffectif',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('ANAPEC', 'ANAPEC')], default='CDI', max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AddField(
            model_name='operateureffectif',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='operateureffectif',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effectifs_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operateureffectif',
            name='ville_actuelle',
            field=models.CharField(default='N/A', max_length=120, verbose_name='Ville actuelle'),
        ),
        migrations.AddField(
            model_name='operateureffectif',
            name='ville_origine',
            field=models.CharField(default='N/A', max_length=120, verbose_name='Ville origine'),
        ),
        migrations.AlterField(
            model_name='operateureffectif',
            name='fonction',
            field=models.CharField(default='Operateur', max_length=120, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='operateureffectif',
            name='niveau_etude',
            field=models.CharField(default='N/A', max_length=120, verbose_name="Niveau d'etude"),
        ),
        migrations.AlterField(
            model_name='operateureffectif',
            name='numero_casier',
            field=models.CharField(default='N/A', max_length=32, verbose_name='Numero de casier'),
        ),
        migrations.AlterField(
            model_name='operateureffectif',
            name='parada_transport',
            field=models.CharField(default='N/A', max_length=120, verbose_name='Parada de transport'),
        ),
        migrations.AlterField(
            model_name='operateureffectif',
            name='pointure_chaussure',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Pointure de chaussure'),
        ),
        migrations.AlterField(
            model_name='operateureffectif',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=10, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='operateureffectif',
            name='specialite',
            field=models.CharField(default='N/A', max_length=120, verbose_name='Specialite'),
        ),
        migrations.AlterField(
            model_name='operateureffectif',
            name='taille_pantalon',
            field=models.CharField(default='M', max_length=20, verbose_name='Taille pantalon'),
        ),
        migrations.AlterField(
            model_name='operateureffectif',
            name='taille_veste',
            field=models.CharField(default='M', max_length=20, verbose_name='Taille veste'),
        ),
    ]
