# Generated by Django 6.0.4 on 2026-04-27 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_operateureffectif_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(choices=[('Berceau', 'Berceau'), ('CCB', 'CCB')], max_length=20, verbose_name='Equipe')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif')),
                ('remplacant', models.CharField(blank=True, max_length=180, verbose_name='Remplacant')),
                ('nom_complet', models.CharField(max_length=180, verbose_name='Nom complet')),
                ('date_absence', models.DateField(verbose_name='Date absence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_absence', 'nom_complet'],
                'indexes': [models.Index(fields=['date_absence'], name='absence_date_idx'), models.Index(fields=['nom_complet'], name='absence_nom_idx'), models.Index(fields=['motif'], name='absence_motif_idx')],
                'constraints': [models.UniqueConstraint(fields=('nom_complet', 'date_absence', 'equipe'), name='uniq_absence_nom_date_equipe')],
            },
        ),
    ]
