# Generated by Django 6.0.4 on 2026-04-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateureffectif',
            name='shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('N', 'N')], default='A', max_length=1, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='productionberceau',
            name='shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('N', 'N')], max_length=1, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='productionccb',
            name='shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('N', 'N')], max_length=1, verbose_name='Shift'),
        ),
    ]
