# Generated by Django 6.0.4 on 2026-04-27 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_operateureffectif_shift_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeDegrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(choices=[('Berceau', 'Berceau'), ('CCB', 'CCB')], max_length=20, verbose_name='Equipe')),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('N', 'N')], max_length=1, verbose_name='Shift')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('probleme', models.CharField(max_length=255, verbose_name='Probleme')),
                ('pilote', models.CharField(max_length=180, verbose_name='Pilote')),
                ('date', models.DateField(verbose_name='Date')),
                ('delai', models.DateField(verbose_name='Delai')),
                ('cause', models.CharField(max_length=255, verbose_name='Cause')),
                ('statut', models.CharField(choices=[('Ouvert', 'Ouvert'), ('En cours', 'En cours'), ('Clos', 'Clos')], default='Ouvert', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mode_degrade_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'shift'],
                'indexes': [models.Index(fields=['date'], name='mode_degrade_date_idx'), models.Index(fields=['statut'], name='mode_degrade_statut_idx')],
            },
        ),
    ]
