# Generated by Django 6.0.4 on 2026-04-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_modedegrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='equipe',
            field=models.CharField(choices=[('Berceau', 'Berceau')], max_length=20, verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='modedegrade',
            name='equipe',
            field=models.CharField(choices=[('Berceau', 'Berceau')], max_length=20, verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='operateureffectif',
            name='equipe',
            field=models.CharField(choices=[('Berceau', 'Berceau')], max_length=20, verbose_name='Equipe'),
        ),
    ]
