# Generated by Django 6.0.4 on 2026-04-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_absence_equipe_alter_modedegrade_equipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('N', 'N')], default='A', max_length=1, verbose_name='Shift'),
        ),
    ]
