# Generated by Django 6.0.4 on 2026-04-27 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_absence_names_to_effectif(apps, schema_editor):
    Absence = apps.get_model("app", "Absence")
    OperateurEffectif = apps.get_model("app", "OperateurEffectif")

    for absence in Absence.objects.all().iterator():
        legacy_name = (absence.nom_complet or "").strip()
        if not legacy_name:
            absence.migration_status = "a_corriger"
            absence.migration_note = "Absence sans nom legacy; selectionner un effectif."
            absence.save(update_fields=["migration_status", "migration_note"])
            continue

        matches = OperateurEffectif.objects.filter(
            nom_complet__iexact=legacy_name,
            equipe=absence.equipe,
            is_deleted=False,
        ).order_by("id")
        match = matches.first()
        if not match:
            absence.migration_status = "a_corriger"
            absence.migration_note = f"Aucun effectif correspondant pour '{legacy_name}'."
            absence.save(update_fields=["migration_status", "migration_note"])
            continue

        absence.effectif_id = match.id
        absence.shift = match.shift or absence.shift
        absence.migration_status = "ok"
        absence.migration_note = ""
        absence.save(update_fields=["effectif_id", "shift", "migration_status", "migration_note"])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_absence_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['-date_absence', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='absence',
            name='uniq_absence_nom_date_equipe',
        ),
        migrations.RemoveIndex(
            model_name='absence',
            name='absence_nom_idx',
        ),
        migrations.AddField(
            model_name='absence',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='absence',
            name='effectif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='app.operateureffectif', verbose_name='Personne absente'),
        ),
        migrations.AddField(
            model_name='absence',
            name='migration_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Note migration'),
        ),
        migrations.AddField(
            model_name='absence',
            name='migration_status',
            field=models.CharField(choices=[('ok', 'OK'), ('a_corriger', 'A corriger')], default='ok', max_length=20, verbose_name='Statut migration'),
        ),
        migrations.AddField(
            model_name='absence',
            name='remplacant_effectif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remplacements_absence', to='app.operateureffectif', verbose_name='Remplacant (effectif)'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='nom_complet',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Nom complet (legacy)'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='remplacant',
            field=models.CharField(blank=True, max_length=180, verbose_name='Remplacant externe'),
        ),
        migrations.RunPython(migrate_absence_names_to_effectif, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='absence',
            constraint=models.UniqueConstraint(fields=('effectif', 'date_absence', 'equipe'), name='uniq_absence_effectif_date_equipe'),
        ),
    ]
