# Generated by Django 6.0.4 on 2026-04-27 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_useraccessprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BerceauModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BerceauPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='app.berceaumodule')),
            ],
            options={
                'ordering': ['module__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BerceauMoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyens', to='app.berceauposte')),
            ],
            options={
                'ordering': ['poste__module__name', 'poste__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArretBerceau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('N', 'N')], max_length=1)),
                ('heure_production', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('temps_arret_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('commentaire', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrets_berceau_updated', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrets', to='app.berceaumodule')),
                ('moyen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrets', to='app.berceaumoyen')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrets', to='app.berceauposte')),
            ],
            options={
                'ordering': ['-date', 'shift', 'heure_production'],
            },
        ),
        migrations.CreateModel(
            name='PanneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panne_types_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertePanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.TextField()),
                ('solution', models.TextField()),
                ('intervenant_nom', models.CharField(max_length=180)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('N', 'N')], max_length=1)),
                ('heure_production', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('temps_arret_min', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('equipe', models.CharField(default='Berceau', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_pannes_updated', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertes_pannes', to='app.berceaumodule')),
                ('moyen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertes_pannes', to='app.berceaumoyen')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertes_pannes', to='app.berceauposte')),
                ('panne_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertes_pannes', to='app.pannetype')),
            ],
            options={
                'ordering': ['-date', 'shift', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='berceauposte',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='uniq_berceau_poste_module_name'),
        ),
        migrations.AddConstraint(
            model_name='berceaumoyen',
            constraint=models.UniqueConstraint(fields=('poste', 'name'), name='uniq_berceau_moyen_poste_name'),
        ),
        migrations.AddConstraint(
            model_name='arretberceau',
            constraint=models.UniqueConstraint(fields=('module', 'poste', 'moyen', 'date', 'shift', 'heure_production'), name='uniq_arret_berceau_scope'),
        ),
    ]
