# Generated by Django 6.0.4 on 2026-04-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_berceaumodule_berceauposte_berceaumoyen_arretberceau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='berceauposte',
            name='a1_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='berceauposte',
            name='a3_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
