# Generated by Django 6.0.4 on 2026-04-28 10:44

import django.core.validators
from django.db import migrations, models


def backfill_hourly_rebut_retouche(apps, schema_editor):
    ProductionBerceau = apps.get_model("app", "ProductionBerceau")
    for row in ProductionBerceau.objects.all().iterator():
        changed = False
        if (row.rebut or 0) > 0 and sum(getattr(row, f"rebut_h{i}", 0) or 0 for i in range(1, 9)) == 0:
            row.rebut_h1 = row.rebut or 0
            changed = True
        if (row.retouche or 0) > 0 and sum(getattr(row, f"retouche_h{i}", 0) or 0 for i in range(1, 9)) == 0:
            row.retouche_h1 = row.retouche or 0
            changed = True
        if changed:
            row.save(update_fields=["rebut_h1", "retouche_h1"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_berceauposte_a1_enabled_berceauposte_a3_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionberceau',
            name='rebut_h1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rebut H1'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='rebut_h2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rebut H2'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='rebut_h3',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rebut H3'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='rebut_h4',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rebut H4'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='rebut_h5',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rebut H5'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='rebut_h6',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rebut H6'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='rebut_h7',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rebut H7'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='rebut_h8',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rebut H8'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='retouche_h1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retouche H1'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='retouche_h2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retouche H2'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='retouche_h3',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retouche H3'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='retouche_h4',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retouche H4'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='retouche_h5',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retouche H5'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='retouche_h6',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retouche H6'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='retouche_h7',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retouche H7'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='retouche_h8',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Retouche H8'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='validated_hours_mask',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(backfill_hourly_rebut_retouche, noop),
    ]
