# Generated by Django 6.0.4 on 2026-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_productionberceau_rebut_h1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionberceau',
            name='line_h1',
            field=models.CharField(choices=[('A1', 'A1'), ('A3', 'A3')], default='A1', max_length=2, verbose_name='Diversité H1'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='line_h2',
            field=models.CharField(choices=[('A1', 'A1'), ('A3', 'A3')], default='A1', max_length=2, verbose_name='Diversité H2'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='line_h3',
            field=models.CharField(choices=[('A1', 'A1'), ('A3', 'A3')], default='A1', max_length=2, verbose_name='Diversité H3'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='line_h4',
            field=models.CharField(choices=[('A1', 'A1'), ('A3', 'A3')], default='A1', max_length=2, verbose_name='Diversité H4'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='line_h5',
            field=models.CharField(choices=[('A1', 'A1'), ('A3', 'A3')], default='A1', max_length=2, verbose_name='Diversité H5'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='line_h6',
            field=models.CharField(choices=[('A1', 'A1'), ('A3', 'A3')], default='A1', max_length=2, verbose_name='Diversité H6'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='line_h7',
            field=models.CharField(choices=[('A1', 'A1'), ('A3', 'A3')], default='A1', max_length=2, verbose_name='Diversité H7'),
        ),
        migrations.AddField(
            model_name='productionberceau',
            name='line_h8',
            field=models.CharField(choices=[('A1', 'A1'), ('A3', 'A3')], default='A1', max_length=2, verbose_name='Diversité H8'),
        ),
    ]
