# Generated by Django 6.0.4 on 2026-04-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_productionberceau_line_h1_productionberceau_line_h2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertepanne',
            name='intervenant_nom',
        ),
        migrations.AddField(
            model_name='alertepanne',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('kta', 'KTA'), ('logistique', 'Logistique'), ('fabrication', 'Fabrication')], default='fabrication', max_length=20),
        ),
        migrations.AddField(
            model_name='arretberceau',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('kta', 'KTA'), ('logistique', 'Logistique'), ('fabrication', 'Fabrication')], default='fabrication', max_length=20),
        ),
    ]
