# Generated by Django 6.0.4 on 2026-04-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_alertepanne_intervenant_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateureffectif',
            name='psp_lead',
            field=models.ForeignKey(blank=True, help_text='PSP responsable de cette equipe operateur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='app.operateureffectif'),
        ),
    ]
