# Generated by Django 6.0.4 on 2026-04-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_operateureffectif_psp_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operateureffectif',
            name='fonction',
            field=models.CharField(choices=[('PSP', 'PSP'), ('OPERATEUR', 'OPERATEUR')], default='OPERATEUR', max_length=20, verbose_name='Fonction'),
        ),
    ]
