# Generated by Django 6.0.4 on 2026-05-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_prune_relocated_models_state'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccessprofile',
            table='app_useraccessprofile',
        ),
    ]
