"""Référentiels types de panne par équipe (sources uniques pour seeds + API)."""

# Types Berceau — référentiel métier (liste Excel « Problemes » + variantes historiques conservées)
BERCEAU_PANNE_TYPES = [
    "Amorçage",
    "Arrêt",
    "Arrêt de convoyeur",
    "Arrêt programmé",
    "Basculement de A1 à A3",
    "Basculement de A3 à A1",
    "Blocage de coulisseau",
    "Blocage de fil",
    "Blocage de pilote",
    "Blocage de poinçons",
    "Blocage de robot de transfert",
    "Blocage de serrage",
    "Blocage manipulateur",
    "Cable de masse",
    "Changement de bobine de fil",
    "Changement de diffuseur",
    "Changement de torche",
    "Changement des électrodes",
    "Chute de la torche",
    "Chute de pièce",
    "Colision",  # historique (orthographe) — gardé pour les fiches déjà saisies
    "Collision",
    "Décyclage",
    "Défaut de robot MAG",
    "Dégradation de gaine",
    "Fil collé",
    "Fuite d'air",
    "Fuite d'eau",
    "Lancement de soudage",
    "Ligne hors service",
    "Ligne vide",
    "Manque de débit d'eau",
    "Manque de référence",
    "Manque d'emballage",
    "MES",
    "Nettoyage des buses",
    "Perte d'énergie",
    "Poinçonnage",
    "Probleme automate",
    "Probleme de convoyeur",  # historique — distinct de « Arrêt de convoyeur »
    "Problème dans circuit de sécurité",
    "Problème d'ascenseur",
    "Problème de bridage",
    "Problème de capteur",
    "Problème de générateur",
    "Problème de lubrification",
    "Problème de soudage",
    "Problème de vérin",
    "Problème élévateur",
    "Problème GAZ",
    "Problème maquette",
    "Problème pression",
    "Problème teach",
    "Réglage Z-Citrou",
    "Remplissage des réservoirs de lubrification",
]

# Types CCB — hors référentiel Berceau (pas de doublon avec BERCEAU_PANNE_TYPES)
CCB_PANNE_TYPES = [
    "Arrêt programme",
    "Problème qualité pièce",
    "Réglage / mise au point",
    "Maintenance corrective",
    "Manque composant",
    "Attente outillage",
    "Nettoyage ligne",
    "Perte énergie / air",
    "Autre",
]

BERCEAU_PANNE_TYPE_NAMES = frozenset(BERCEAU_PANNE_TYPES)
CCB_PANNE_TYPE_NAMES = frozenset(CCB_PANNE_TYPES)
